name 'cek-pam'
version '0.0.3'

author 'William Hopper, Yuri Arabadji'
license 'Apache License 2.0'
project_page 'https://github.com/celesteking/puppet-module-pam'
source 'https://github.com/celesteking/puppet-module-pam'
summary 'PAM Module for Puppet'
description 'PAM Module for Puppet'
dependency 'ripienaar/concat', '>=0.1.0'
